cards/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('calendar/', include(('userscalendar.urls', 'userscalendar'), namespace='userscalendar')),

    path('', include(('users_cards.urls', 'users_cards'), namespace='users_cards')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_cards/urls.py
from django.urls import path, re_path

from .views import (
    home,
    create_card,
    card_detail,
    card_add_event,
    card_delete,
    event_finished_delete
    )

urlpatterns = [
    path('', home, name='home'),
    path('create/', create_card, name='create'),

    re_path('^(?P<url>[-\w]+)/$', card_detail, name='card_detail'),
    re_path('^(?P<url>[-\w]+)/delete', card_delete, name='card_delete'),

    re_path('^(?P<url>[-\w]+)/create$', card_add_event, name='card_add_event'),

    re_path('^(?P<url>[-\w]+)/(?P<id>\d+)/(?P<slug>[-\w]+)/delete',
            event_finished_delete,
            name='event_finished_delete'
            ),

]

userscalendar/urls.py
from django.urls import path, re_path

from .views import (
    edit_page,
    home_page,
    month_page,
    detail_page,
    create_page,
    create_event,
    event_finished_delete
    )

urlpatterns = [
    path('create/', create_page, name='create_page'),

    re_path('^(?P<slug>[-\w]+)/$', home_page, name='home_page'),
    path('', home_page, name='home_page'),

    re_path('^(?P<url>[-\w]+)/detail/(?P<id>\d+)/$', detail_page, name='detail_page'),

    re_path('^(?P<url>[-\w]+)/detail/(?P<id>\d+)/create_event$', create_event, name='create_event'),
    re_path('^(?P<url>[-\w]+)/detail/(?P<id>\d+)/edit$', edit_page, name='edit_page'),

    re_path('(?P<url>[-\w]+)/month/(?P<month>[-\w]+)/', month_page, name='month_page'),

    re_path('^(?P<url>[-\w]+)/detail/(?P<id>\d+)/(?P<slug>[-\w]+)',
            event_finished_delete,
            name='event_finished_delete'
            ),


]

templates/home/add_event.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3 class="alert alert-info">Create event:</h3>

        <form action="{% url "users_cards:card_add_event" url=url %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Create">
        </form>
    </div>


{% endblock %}

templates/home/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en" class="full-height">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/compiled.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <link rel="stylesheet" href="{% static "css/custom_style.css" %}">
    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    {% block head %}
    {% endblock %}

</head>
<body style="background: linear-gradient(#f5f7fa, #c3cfe2);">

    <div style="background: linear-gradient(#f5f7fa, #c3cfe2);">
        <br><br>
        {% block content %}

        {% endblock %}
        <br>
    </div>

    <style>
        .asteriskField {
            display: none;
        }
    </style>
    
    <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>

    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/compiled.min.js" %}"></script>
</body>
</html>

templates/home/calendar.html
{% extends "home/base.html" %}

{% block content %}
    <div class="container">
            <div class="row">
                <h3 class="alert alert-info">Calendar:</h3>
            </div>
            <h3 class="alert alert-light">{{ calendar.name }}</h3>
            <h3 class="alert alert-light">{{ calendar.content }}</h3>
            {% if calendar.image %}
                <img class="this" src="{{ calendar.image.url }}" alt="">
            {% endif %}
            <br><br>
            <style>
                .this{
                    width: 140px;
                }
            </style>

            <div class="row">
                <h3 class="btn btn-success btn-lg">Select month:</h3>
            </div>
            <br>
            <hr>
            <div class="row">
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="September"  %}">September</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="October"  %}">October</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="November"  %}">November</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="December"  %}">December</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="January"  %}">January</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="February"  %}">February</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="Mart"  %}">Mart</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="April"  %}">April</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="March"  %}">March</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="June"  %}">June</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="July"  %}">July</a>
                    <a class="btn btn-light-blue" href="{% url "userscalendar:month_page" url=calendar_url month="August"  %}">August</a>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-1"></div>
                <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">September:</h2>
                                <br>
                            </div>
                        </div>
                {% for obj in objects %}
                    {% if forloop.counter0|divisibleby:10 %}
                        </div><br><br><div class="row" style="margin-bottom: -50px;">
                    {% endif %}
                    {% if forloop.counter == 31 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger" style="margin-top: 20px;">October:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 62 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">November:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 92 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">December:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 123 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">January:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 154 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">February:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 183 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">March:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 214 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">April:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 244 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">May:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 275 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">June:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 305 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">July:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    {% if forloop.counter == 336 %}
                        <br><br><br><br>
                        <div class="container">
                            <div class="row">
                                <br><br>
                                <h2 class="alert alert-danger">August:</h2>
                                <br><br>
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-xs-1" style="word-wrap:break-word;">
                        <a href="{% url "userscalendar:detail_page" url=calendar_url id=obj.id %}">
                            <h2 class="text-center alert alert-success m-1" style="width: 200px;">{{ obj.day_in_month|truncatechars:8 }}</h2>
                        </a>
                    </div>
                {% endfor %}
        </div>
    </div>

{% endblock %}

templates/home/create_calendar.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3 class="alert alert-info">Create calendar:</h3>

        <form action="{% url "userscalendar:create_page" %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Create">
        </form>
    </div>


{% endblock %}

templates/home/create_card.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3 class="alert alert-info">Create card:</h3>

        <form action="{% url "users_cards:create" %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Create">
        </form>
    </div>


{% endblock %}

templates/home/create_event_calendar.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3 class="alert alert-info">Create card:</h3>

        <form action="{% url "userscalendar:create_event" url=url id=calendar_id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Create">
        </form>
    </div>


{% endblock %}

templates/home/detail.html
{% extends "home/base.html" %}

{% block content %}
    <div class="container">
        <h2 class="alert alert-light">Card: {{ card.title }}</h2>
        <h4 class="alert alert-dismissible">Description: {{ card.content }}</h4>

        {% if card.image %}
            <img src="{{ card.image.url }}" class="this text-center rounded-circle">
        {% endif %}
        <br>

            <a href="{% url "users_cards:card_add_event" url=card.url %}" class="btn btn-success">Add event</a>

            <a href="{% url "users_cards:card_delete" url=card.url %}" class="btn btn-danger">Delete this card</a>

        <hr>

        <h1 class="alert alert-info text-center">Future events:</h1>
        <hr>

        <style>
            .this{
                width: 320px;
            }
        </style>

        <div class="row">
            {% for obj in objects %}
                {% if not obj.finished %}
                    {% if forloop.counter0|divisibleby:3 %}
                        </div><br><br><div class="row">
                    {% endif %}
                        <div class="col-xs-4 col-lg-4">
                            <div class="card card-cascade width_card" style="margin-bottom: 20px; width: 320px;">
                              <div class="view view-cascade overlay">
                                  {% if obj.image %}
                                        <div class="text-center avatar mx-auto white">
                                            <img src="{{ obj.image.url }}" class="this text-center rounded-circle">
                                        </div>
                                    {% endif %}
                                      <div class="mask flex-center rgba-black-strong">
                                        <p class="white-text">Title: {{ obj.title }}</p>
                                    </div>
                              </div>
                              <div class="card-body card-body-cascade text-center">
                                <p class="card-text">Content: {{ obj.content }}</p>
                                <a class="text-left btn btn-warning" href="{% url "users_cards:event_finished_delete" url=card.url id=obj.id slug='finished' %}">Finished</a>
                                <a class="text-left btn btn-danger" href="{% url "users_cards:event_finished_delete" url=card.url id=obj.id slug='delete' %}">Delete</a>

                              </div>
                            </div>
                        </div>
                {% endif %}
            {% endfor %}

            </div>
        <br>
        <h1 class="alert alert-success text-center">Recent:</h1>
        <div class="row">
            {% for obj in objects %}
                {% if obj.finished %}
                    {% if forloop.counter0|divisibleby:3 %}
                            </div><br><br><div class="row">
                        {% endif %}
                            <div class="col-xs-4 col-lg-4">
                                <div class="card card-cascade width_card" style="margin-bottom: 20px; width: 320px;">
                                  <div class="view view-cascade overlay">
                                      {% if obj.image %}
                                            <div class="text-center avatar mx-auto white">
                                                <img src="{{ obj.image.url }}" class="this text-center rounded-circle">
                                            </div>
                                        {% endif %}
                                          <div class="mask flex-center rgba-black-strong">
                                            <p class="white-text">Title: {{ obj.title }}</p>
                                        </div>
                                  </div>
                                  <div class="card-body card-body-cascade text-center">
                                    <p class="card-text">Content: {{ obj.content }}</p>
                                    <a class="text-left btn btn-warning" href="{% url "users_cards:event_finished_delete" url=card.url id=obj.id slug='finished' %}">Finished</a>
                                    <a class="text-left btn btn-danger" href="{% url "users_cards:event_finished_delete" url=card.url id=obj.id slug='delete' %}">Delete</a>

                                  </div>
                                </div>
                            </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

templates/home/detail_calendar.html
{% extends "home/base.html" %}

{% block content %}
    <div class="container">
        <h2 class="alert alert-info">Detail page for {{ obj.day }} day:</h2>
        <hr>
        <br>
        <h3>Event name: {{ obj.name }}</h3>
        <h4>Description: {{ obj.content }}</h4>
        {% if obj.image %}
            <img src="{{ obj.image.url }}" alt="">
        {% endif %}
        <a class="btn btn-success" href="{% url "userscalendar:create_event" url=url id=obj.id %}">Add new event</a>
        <a class="btn btn-success" href="{% url "userscalendar:edit_page" url=url id=obj.id %}">Edit day</a>
        <br>
        <a class="btn btn-info" href="{% url "userscalendar:home_page" slug=url %}">Back</a>

        <style>
            .this{
                width: 320px;
            }
        </style>

        <br><br>
        <h2 class="alert alert-success text-center">Events:</h2>

        <div class="row">
            {% for obj in objects %}
                {% if not obj.finished %}
                    {% if forloop.counter0|divisibleby:3 %}
                        </div><br><br><div class="row">
                    {% endif %}
                        <div class="col-xs-4 col-lg-4">
                            <div class="card card-cascade width_card" style="margin-bottom: 20px; width: 320px;">
                              <div class="view view-cascade overlay">
                                  {% if obj.image %}
                                        <div class="text-center avatar mx-auto white">
                                            <img src="{{ obj.image.url }}" class="this text-center rounded-circle">
                                        </div>
                                    {% endif %}
                                      <div class="mask flex-center rgba-black-strong">
                                        <p class="white-text">Title: {{ obj.title }}</p>
                                    </div>
                              </div>
                              <div class="card-body card-body-cascade text-center">
                                <p class="card-text">Content: {{ obj.content }}</p>
                                <a class="text-left btn btn-warning" href="{% url "userscalendar:event_finished_delete" url=url_id id=obj.id slug="finished" %}">Finished</a>
                                <a class="text-left btn btn-danger" href="{% url "userscalendar:event_finished_delete" url=url_id id=obj.id slug="delete" %}">Delete</a>

                              </div>
                            </div>
                        </div>
                {% endif %}
            {% endfor %}

            </div>
        <br>
        <h1 class="alert alert-success text-center">Recent:</h1>
        <div class="row">
            {% for obj in objects %}
                {% if obj.finished %}
                    {% if forloop.counter0|divisibleby:3 %}
                            </div><br><br><div class="row">
                        {% endif %}
                            <div class="col-xs-4 col-lg-4">
                                <div class="card card-cascade width_card" style="margin-bottom: 20px; width: 320px;">
                                  <div class="view view-cascade overlay">
                                      {% if obj.image %}
                                            <div class="text-center avatar mx-auto white">
                                                <img src="{{ obj.image.url }}" class="this text-center rounded-circle">
                                            </div>
                                        {% endif %}
                                          <div class="mask flex-center rgba-black-strong">
                                            <p class="white-text">Title: {{ obj.title }}</p>
                                        </div>
                                  </div>
                                  <div class="card-body card-body-cascade text-center">
                                    <p class="card-text">Content: {{ obj.content }}</p>
                                    <a class="text-left btn btn-danger" href="{% url "userscalendar:event_finished_delete" url=url_id id=obj.id slug="delete" %}">Delete</a>

                                  </div>
                                </div>
                            </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>


{% endblock %}

templates/home/edit_calendar_page.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3 class="alert alert-info">Edit calendar:</h3>

        <form action="{% url "userscalendar:detail_page" id=day_id url=url %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Create">
        </form>
    </div>


{% endblock %}

templates/home/home_page.html
{% extends "home/base.html" %}

{% block content %}
    <a href="{% url "users_cards:create" %}" class="btn btn-success">Create card</a>
    <a href="{% url "userscalendar:create_page" %}" class="btn btn-success">Create calendar</a>
{% endblock %}

templates/home/month_page.html
{% extends "home/base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2 class="alert alert-info">Detail page for {{ month }}:</h2>
        </div>
        <div class="row">
            {% for objects in obj %}
                <a href="{% url "userscalendar:detail_page" url=objects.calendar_url id=objects.id %}">
                    <h2 class="text-center alert alert-success m-1" style="width: 200px;"> {{ objects.day_in_month }}|{{ objects.name|truncatechars:8 }}</h2>
                </a>
            {% endfor %}
        </div>
    </div>

{% endblock %}